import assert from 'assert';
import fs from 'node:fs';
import * as UAP from './uap.js';
import { hash256 } from './sha256.js';

// Cross-implementation check of signatureHash() against the C++ node's own
// fixture, src/test/data/sighash.json, which src/test/sighash_tests.cpp
// consumes as sighash_from_data. Every vector is
//
//     [raw_transaction, script, input_index, hashType, signature_hash]
//
// with the leading row a column-name comment. The expected hash is stored as
// uint256::GetHex(), i.e. reversed into display order.
//
// This is the only place uap.js's signatureHash is checked against anything
// other than itself. The rest of the suite signs transactions this same code
// built, so an error in the preimage would verify happily against its own
// mistake; these 500 vectors were generated by a different implementation in
// a different language and pin the byte layout from outside.
//
// Two things this fixture cannot cover, because they need RandomTransaction
// or RandomScript to do something those generators never do:
//
// The degenerate "hash of 1" returns: RandomTransaction draws nIn in range
// and gives SIGHASH_SINGLE an output for every input, so neither degenerate
// path is reachable from these 500 vectors. SIGHASH_DEGENERATE_HASH in
// uap.js was untested by everything here.
//
// A scriptCode ending in a truncated push, where the node writes a length
// prefix longer than the bytes it then emits. RandomScript only emits
// single-byte opcodes, so it never produces a push at all, let alone a
// truncated one; deleting the scriptSigLength override in uap.js survived
// every assertion in this file for that reason.
//
// Both gaps are closed below by src/test/data/sighash_uap.json, a small
// hand-constructed fixture from the same C++ oracle (sighash_uap_edge_cases
// in src/test/sighash_tests.cpp) rather than by anything in this 500-vector
// section.

const VECTORS = '../../src/test/data/sighash.json';
const UAP_EDGE_VECTORS = '../../src/test/data/sighash_uap.json';

// ---- minimal transaction parser ----
//
// Deliberately local to this test rather than exported from uap.js. Nothing
// in production parses raw transaction bytes -- every consumer, including
// integration.test.js and contrib/uap-web, gets transactions from the node
// as decoded JSON via getrawtransaction's verbose form -- and a signing
// library should not grow public API to serve a test.
//
// Its correctness is not taken on trust: every vector is re-serialized and
// compared against the input hex below, which makes a parser bug fail loudly
// instead of quietly feeding a wrong transaction into the hash.
function makeReader(bytes) {
  let pos = 0;
  const need = (n) => {
    if (pos + n > bytes.length) throw new Error(`truncated at ${pos}, wanted ${n} more`);
  };
  return {
    u8() {
      need(1);
      return bytes[pos++];
    },
    uint32() {
      need(4);
      const v = bytes[pos] | (bytes[pos + 1] << 8) | (bytes[pos + 2] << 16) | (bytes[pos + 3] << 24);
      pos += 4;
      return v >>> 0;
    },
    int64() {
      need(8);
      const v = new DataView(bytes.buffer, bytes.byteOffset + pos, 8).getBigInt64(0, true);
      pos += 8;
      return v;
    },
    take(n) {
      need(n);
      const out = bytes.slice(pos, pos + n);
      pos += n;
      return out;
    },
    varint() {
      const first = this.u8();
      if (first < 0xfd) return first;
      if (first === 0xfd) {
        need(2);
        const v = bytes[pos] | (bytes[pos + 1] << 8);
        pos += 2;
        return v;
      }
      if (first === 0xfe) return this.uint32();
      throw new Error('8-byte varint in a fixture transaction');
    },
    atEnd() {
      return pos === bytes.length;
    },
  };
}

function parseTx(hex) {
  const r = makeReader(UAP.hexToBytes(hex));
  const tx = { version: r.uint32(), vin: [], vout: [] };
  const nIn = r.varint();
  for (let i = 0; i < nIn; i++) {
    const txidLE = r.take(32);
    const txid = UAP.bytesToHex(Uint8Array.from(txidLE).reverse());
    const vout = r.uint32();
    const scriptSig = r.take(r.varint());
    tx.vin.push({ txid, vout, scriptSig, sequence: r.uint32() });
  }
  const nOut = r.varint();
  for (let i = 0; i < nOut; i++) {
    const value = r.int64();
    assert(
      value <= BigInt(Number.MAX_SAFE_INTEGER) && value >= -BigInt(Number.MAX_SAFE_INTEGER),
      'fixture output value does not fit a JS number'
    );
    tx.vout.push({ value: Number(value), scriptPubKey: r.take(r.varint()) });
  }
  tx.locktime = r.uint32();
  assert(r.atEnd(), 'trailing bytes after a fixture transaction');
  return tx;
}

const raw = JSON.parse(fs.readFileSync(new URL(VECTORS, import.meta.url), 'utf8'));
const vectors = raw.filter((row) => row.length === 5);
assert(vectors.length > 400, `expected the full fixture, got ${vectors.length} vectors`);

// The fixture only exercises signatureHash if it reaches scripts with an
// OP_CODESEPARATOR in them -- that is the single case where splicing
// scriptCode in verbatim differs from what the node does. Assert the corpus
// still contains those, so that trimming or regenerating sighash.json can't
// silently turn this file into 500 passing tests of nothing.
const withCodeSeparator = vectors.filter((v) => UAP.hexToBytes(v[1]).includes(0xab));
assert(
  withCodeSeparator.length > 50,
  `fixture no longer covers OP_CODESEPARATOR (${withCodeSeparator.length} vectors)`
);

// Shared by both fixtures below: parse, round-trip, hash, compare. Pulled
// out to a function once there were two JSON files with the same 5-column
// shape to walk, rather than duplicating the loop body.
function checkVectors(rows) {
  let n = 0;
  for (const [rawTx, scriptHex, nIn, hashType, expected] of rows) {
    const tx = parseTx(rawTx);

    // Round-trip first: this is what makes the parser trustworthy, and it is
    // free coverage of serializeTx as a side effect of every vector checked.
    assert.strictEqual(UAP.txToHex(tx), rawTx, `re-serialization differs for ${rawTx.slice(0, 32)}...`);

    const got = UAP.signatureHash(UAP.hexToBytes(scriptHex), tx, nIn, hashType);
    const display = UAP.bytesToHex(Uint8Array.from(got).reverse());
    assert.strictEqual(
      display,
      expected,
      `sighash mismatch (nIn=${nIn} hashType=${hashType} script=${scriptHex})`
    );
    n++;
  }
  return n;
}

let checked = checkVectors(vectors);

// ---- the two gaps the 500 vectors above cannot reach ----
//
// src/test/data/sighash_uap.json is produced by sighash_uap_edge_cases in
// src/test/sighash_tests.cpp: eight hand-built vectors, not random ones,
// covering (a) nIn out of range, (b) SIGHASH_SINGLE with no matching output
// -- the two SIGHASH_DEGENERATE_HASH returns -- (c) and (h) a scriptCode
// ending in a truncated push (with and without a preceding
// OP_CODESEPARATOR) -- the scriptSigLength override -- plus (d) an
// all-OP_CODESEPARATOR script, (e) hashType 0, (f) ANYONECANPAY with a
// signed input other than vin[0], and (g) SIGHASH_SINGLE combined with
// ANYONECANPAY. Same 5-column shape as sighash.json, so it needs no separate
// parser -- checkVectors handles both.
const uapEdgeRaw = JSON.parse(fs.readFileSync(new URL(UAP_EDGE_VECTORS, import.meta.url), 'utf8'));
const uapEdgeVectors = uapEdgeRaw.filter((row) => row.length === 5);
assert.strictEqual(uapEdgeVectors.length, 8, `expected all 8 hand-built edge vectors, got ${uapEdgeVectors.length}`);
checked += checkVectors(uapEdgeVectors);

// ---- what the fixture cannot reach: 0xab inside a data push ----
//
// RandomScript in src/test/sighash_tests.cpp only ever emits single-byte
// opcodes, so not one of the 500 vectors contains a data push. That leaves
// the most dangerous half of the stripping rule untested by them: 0xab is
// only an OP_CODESEPARATOR when it appears as an opcode. The same byte
// inside a push is data, and removing it would silently sign a different
// script than the one being spent. Mutating the opcode walk to ignore push
// payloads passes all 500 vectors.
//
// The oracle here is not this implementation. A scriptCode with no
// OP_CODESEPARATOR *opcode* must be signed verbatim, so the preimage is
// exactly serializeTx of the transaction with that script spliced into the
// signed input -- built independently below, and itself pinned by the 500
// round-trips above.
{
  const tx = {
    version: 1,
    locktime: 0,
    vin: [{ txid: 'aa'.repeat(32), vout: 0, scriptSig: new Uint8Array(0), sequence: 0xffffffff }],
    vout: [{ value: 1000, scriptPubKey: UAP.hexToBytes('51') }],
  };

  const scripts = {
    'a 2-byte push of 0xab 0xab': '02abab',
    'OP_PUSHDATA1 carrying 0xab': '4c03ababab',
    'OP_PUSHDATA2 carrying 0xab': '4d0200abab',
    'a push of 0xab next to a real one': '01ab',
  };

  for (const [what, hex] of Object.entries(scripts)) {
    const scriptCode = UAP.hexToBytes(hex);
    const expected = hash256(
      UAP.concatBytes(
        UAP.serializeTx({ ...tx, vin: [{ ...tx.vin[0], scriptSig: scriptCode }] }),
        Uint8Array.of(UAP.SIGHASH_ALL, 0, 0, 0)
      )
    );
    assert.strictEqual(
      UAP.bytesToHex(UAP.signatureHash(scriptCode, tx, 0, UAP.SIGHASH_ALL)),
      UAP.bytesToHex(expected),
      `${what} must be signed verbatim -- 0xab is data here, not an opcode`
    );
  }

  // And the opcode form really is stripped, so the assertions above are not
  // just saying "nothing is ever removed".
  const bare = UAP.hexToBytes('51');
  const separated = UAP.hexToBytes('51ab');
  assert.strictEqual(
    UAP.bytesToHex(UAP.signatureHash(separated, tx, 0, UAP.SIGHASH_ALL)),
    UAP.bytesToHex(UAP.signatureHash(bare, tx, 0, UAP.SIGHASH_ALL)),
    'a trailing OP_CODESEPARATOR opcode must vanish from the preimage'
  );
}

console.log(`sighash-vectors: ${checked} C++ vectors matched`);
