package uaptx

// Cross-implementation check of SignatureHash() against the C++ node's own
// fixture, src/test/data/sighash.json (consumed by sighash_tests.cpp as
// sighash_from_data) plus src/test/data/sighash_uap.json, a small
// hand-built companion covering the degenerate "hash of 1" returns and a
// scriptCode ending in a truncated push. Both files are read from the real
// node checkout at /home/chromatic/dev/whippet -- READ ONLY, never write
// there.
//
// Each row is [raw_transaction, script, input_index, hashType,
// signature_hash], with the first row a column-name comment. The expected
// hash is uint256::GetHex(), i.e. reversed into display order.
//
// This mirrors contrib/uap-js/sighash-vectors.test.js exactly, including
// its local from-scratch transaction parser (deliberately not exported
// production API -- nothing in this package parses raw transaction bytes
// otherwise) and its round-trip-before-hash discipline, which makes a
// parser bug fail loudly rather than quietly feeding a wrong transaction
// into SignatureHash.

import (
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

const (
	sighashVectorsPath = "/home/chromatic/dev/whippet/src/test/data/sighash.json"

	// sighash_uap.json (the sighash_uap_edge_cases oracle) does not exist in
	// the /home/chromatic/dev/whippet checkout -- that tree predates the
	// commit that added sighash_uap_edge_cases to sighash_tests.cpp. It does
	// exist, already committed, in this worktree
	// (src/test/data/sighash_uap.json, generated by the same C++ test on
	// this branch), so that copy is used instead. sighash.json itself is
	// byte-identical between the two checkouts.
	sighashUAPVectorsPath = "../../src/test/data/sighash_uap.json"
)

type txReader struct {
	b   []byte
	pos int
}

func (r *txReader) need(n int) {
	if r.pos+n > len(r.b) {
		panic(fmt.Sprintf("truncated at %d, wanted %d more", r.pos, n))
	}
}

func (r *txReader) u8() byte {
	r.need(1)
	v := r.b[r.pos]
	r.pos++
	return v
}

func (r *txReader) uint32() uint32 {
	r.need(4)
	v := binary.LittleEndian.Uint32(r.b[r.pos:])
	r.pos += 4
	return v
}

func (r *txReader) int64() int64 {
	r.need(8)
	v := int64(binary.LittleEndian.Uint64(r.b[r.pos:]))
	r.pos += 8
	return v
}

func (r *txReader) take(n int) []byte {
	r.need(n)
	out := make([]byte, n)
	copy(out, r.b[r.pos:r.pos+n])
	r.pos += n
	return out
}

func (r *txReader) varint() uint64 {
	first := r.u8()
	if first < 0xfd {
		return uint64(first)
	}
	if first == 0xfd {
		r.need(2)
		v := uint64(r.b[r.pos]) | uint64(r.b[r.pos+1])<<8
		r.pos += 2
		return v
	}
	if first == 0xfe {
		return uint64(r.uint32())
	}
	panic("8-byte varint in a fixture transaction")
}

func (r *txReader) atEnd() bool {
	return r.pos == len(r.b)
}

func parseFixtureTx(t *testing.T, hexStr string) Tx {
	t.Helper()
	raw, err := hex.DecodeString(hexStr)
	if err != nil {
		t.Fatalf("bad hex: %v", err)
	}
	r := &txReader{b: raw}
	tx := Tx{Version: r.uint32()}
	nIn := r.varint()
	for i := uint64(0); i < nIn; i++ {
		txidLE := r.take(32)
		txid := hex.EncodeToString(reverseBytes(txidLE))
		vout := r.uint32()
		scriptSig := r.take(int(r.varint()))
		sequence := r.uint32()
		tx.Vin = append(tx.Vin, TxIn{Txid: txid, Vout: vout, ScriptSig: scriptSig, Sequence: sequence})
	}
	nOut := r.varint()
	for i := uint64(0); i < nOut; i++ {
		value := r.int64()
		scriptPubKey := r.take(int(r.varint()))
		tx.Vout = append(tx.Vout, TxOut{Value: value, ScriptPubKey: scriptPubKey})
	}
	tx.Locktime = r.uint32()
	if !r.atEnd() {
		t.Fatalf("trailing bytes after a fixture transaction")
	}
	return tx
}

func loadVectorRows(t *testing.T, path string) [][]json.RawMessage {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	var raw [][]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		t.Fatalf("parsing %s: %v", path, err)
	}
	var rows [][]json.RawMessage
	for _, row := range raw {
		if len(row) == 5 {
			rows = append(rows, row)
		}
	}
	return rows
}

func decodeRow(t *testing.T, row []json.RawMessage) (rawTx, scriptHex string, nIn int, hashType uint32) {
	t.Helper()
	if err := json.Unmarshal(row[0], &rawTx); err != nil {
		t.Fatalf("row[0]: %v", err)
	}
	if err := json.Unmarshal(row[1], &scriptHex); err != nil {
		t.Fatalf("row[1]: %v", err)
	}
	if err := json.Unmarshal(row[2], &nIn); err != nil {
		t.Fatalf("row[2]: %v", err)
	}
	var ht int64
	if err := json.Unmarshal(row[3], &ht); err != nil {
		t.Fatalf("row[3]: %v", err)
	}
	hashType = uint32(int32(ht))
	return
}

// checkVectors is shared between both fixtures: parse, round-trip, hash,
// compare.
func checkVectors(t *testing.T, rows [][]json.RawMessage) int {
	t.Helper()
	n := 0
	for _, row := range rows {
		rawTx, scriptHex, nIn, hashType := decodeRow(t, row)
		var expected string
		if err := json.Unmarshal(row[4], &expected); err != nil {
			t.Fatalf("row[4]: %v", err)
		}

		tx := parseFixtureTx(t, rawTx)

		if got := TxToHex(tx); got != rawTx {
			t.Fatalf("re-serialization differs for %s...: got %s", rawTx[:min(32, len(rawTx))], got)
		}

		scriptCode, err := hex.DecodeString(scriptHex)
		if err != nil {
			t.Fatalf("bad script hex: %v", err)
		}
		gotHash := SignatureHash(scriptCode, tx, nIn, hashType)
		display := hex.EncodeToString(reverseBytes(gotHash[:]))
		if display != expected {
			t.Fatalf("sighash mismatch (nIn=%d hashType=%d script=%s): got %s want %s", nIn, hashType, scriptHex, display, expected)
		}
		n++
	}
	return n
}

func TestSignatureHashAgainstCPPFixture(t *testing.T) {
	rows := loadVectorRows(t, sighashVectorsPath)
	if len(rows) <= 400 {
		t.Fatalf("expected the full fixture, got %d vectors", len(rows))
	}

	// Assert the corpus still contains OP_CODESEPARATOR (0xab) scripts, so
	// trimming or regenerating sighash.json can't silently turn this test
	// into 500 passing checks of nothing.
	withCodeSeparator := 0
	for _, row := range rows {
		var scriptHex string
		if err := json.Unmarshal(row[1], &scriptHex); err != nil {
			t.Fatalf("row[1]: %v", err)
		}
		scriptBytes, err := hex.DecodeString(scriptHex)
		if err != nil {
			t.Fatalf("bad script hex: %v", err)
		}
		for _, b := range scriptBytes {
			if b == 0xab {
				withCodeSeparator++
				break
			}
		}
	}
	if withCodeSeparator <= 50 {
		t.Fatalf("fixture no longer covers OP_CODESEPARATOR (%d vectors)", withCodeSeparator)
	}

	checked := checkVectors(t, rows)
	t.Logf("sighash.json: %d vectors matched", checked)

	uapRows := loadVectorRows(t, sighashUAPVectorsPath)
	if len(uapRows) != 8 {
		t.Fatalf("expected all 8 hand-built edge vectors, got %d", len(uapRows))
	}
	uapChecked := checkVectors(t, uapRows)
	t.Logf("sighash_uap.json: %d vectors matched", uapChecked)

	t.Logf("sighash-vectors: %d C++ vectors matched", checked+uapChecked)
}
